### ISSUE TITLE
XLM-R instead of XLM ?

### ISSUE THREAD

**Issue by Neuronys** [CZWin32768/XNLG#5]
Hi @CZWin32768 
Have you tried to use the latest XLM-R instead of XLM ?
https://github.com/facebookresearch/XLM
(https://arxiv.org/abs/1911.02116)
Theoretically it should improve your results.
Could you please guide me on how to do it ?
Thanks in advance
Philippe

**Comment by CZWin32768** [comment]
I haven't tried XLM-R, and I also think it would improve the results. 
Maybe you can directly use the XLM-R (or the first few layers) as the encoder, and initialize the XNLG decoder with XLM-R. Because the output sentence is controlled by the target language tag, the language embeddings should be used in the decoder.
Then, train the model with the pre-training protocol of XNLG (the second stage).
